spring:
  application:
    name: connect-backend
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:test}

# Swagger Configuration
springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

# CORS Configuration (autorise Angular en dev)
cors:
  allowed-origins: ${HOST_NAME_CORS:http://localhost:4200}
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  allowed-headers: "*"
  allow-credentials: true