spring:
  application:
    name: connect-backend

  datasource:
    url: jdbc:mysql://localhost:3306/connectdb
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# JWT Configuration
jwt:
  secret: YourSecretKeyForJWTGenerationConnectBackend
  expiration: 3600000

# Swagger Configuration
springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

# Server Configuration
server:
  port: 8085

# CORS Configuration (autorise Angular en dev)
cors:
  allowed-origins: "http://localhost:4200"
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  allowed-headers: "*"
  allow-credentials: true