spring:
  application:
    name: connect-backend
  profiles:
    active: dev
server:
  port: 8085

# Swagger (désactivable en prod via profile)
springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

# CORS (valeur par défaut)
cors:
  allowed-origins: "http://localhost:4200"
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  allowed-headers: "*"
  allow-credentials: true

logging:
  level:
    root: INFO